[build]
  publish = "public" # 또는 index.html이 들어있는 폴더명

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/api/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/server/auth/:splat"
  status = 200